{{- if .Values.global.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "generic-app.fullname" .) .Values.global.serviceAccount.name }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
  {{- with (.Values.global.serviceAccount.annotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
